# Generated by Django 4.1.7 on 2023-08-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="books",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.books",
                verbose_name="Книги",
            ),
        ),
    ]
