# Generated by Django 4.1.7 on 2023-08-04 09:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_books_author_alter_books_description_readers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="is_creation",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="is_editing",
            new_name="edited_at",
        ),
        migrations.RenameField(
            model_name="books",
            old_name="is_creation",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="books",
            old_name="is_editing",
            new_name="edited_at",
        ),
        migrations.RenameField(
            model_name="readers",
            old_name="is_creation",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="readers",
            old_name="is_editing",
            new_name="edited_at",
        ),
        migrations.AlterField(
            model_name="readers",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="номер телефона"
            ),
        ),
    ]
