# Generated by Django 4.1.7 on 2023-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_rename_is_creation_author_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="author",
            name="edited_at",
        ),
        migrations.RemoveField(
            model_name="books",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="books",
            name="edited_at",
        ),
        migrations.RemoveField(
            model_name="readers",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="readers",
            name="edited_at",
        ),
        migrations.AddField(
            model_name="author",
            name="created",
            field=models.DateTimeField(null=True, verbose_name="Дата создания"),
        ),
        migrations.AddField(
            model_name="author",
            name="updated",
            field=models.DateTimeField(
                null=True, verbose_name="Дата последнего обновления"
            ),
        ),
        migrations.AddField(
            model_name="books",
            name="created",
            field=models.DateTimeField(null=True, verbose_name="Дата создания"),
        ),
        migrations.AddField(
            model_name="books",
            name="updated",
            field=models.DateTimeField(
                null=True, verbose_name="Дата последнего обновления"
            ),
        ),
        migrations.AddField(
            model_name="readers",
            name="created",
            field=models.DateTimeField(null=True, verbose_name="Дата создания"),
        ),
        migrations.AddField(
            model_name="readers",
            name="updated",
            field=models.DateTimeField(
                null=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
